- hosts: servers
  tasks:
  - name: apt-update
    become: yes
    apt: 
       update_cache: yes

  - name: apt-install pip
    become: yes
    apt:
      name: python3-pip

  - name: installing flask
    become: yes
    pip:
       name: flask

  - name: installing gunicorn
    become: yes
    pip:
      name: gunicorn

  - name: Installing snmpd
    become: yes
    apt:
      name: snmpd

  - name: binary files copy snmpd
    become: yes
    copy:
     src: ./snmp
     dest: /etc/snmp/snmpd.conf

  - name: Restarting snmpd 
    become: yes
    ansible.builtin.service:
     name: snmpd
     state: restarted


  - name: Executing Application 
    file: 
      state: absent
      path: /home/ubuntu/app2.py

  - name: copy application2.py
    copy:
     src: ./application2.py
     dest: ~/app.py

  - name: transplant gunirun
    copy:
     src: ./gunirun.sh
     dest: ~/gunirun.sh

  - name: Change PWD to another path
    become: yes
    shell: bash /home/ubuntu/gunirun.sh 
